const mongoose = require('mongoose')
const Schema = mongoose.Schema

const schools_v1Schema = new Schema({
  uuid: String,
  opeid: String,
  opeid6: String,
  name_en: String,
  name_jp: String,
  institutionData: {
    uuid: String,
    unitid: String,
    name_en: String,
    name_jp: String,
    card_img_src: String,
    card_img_alt: String,
    page_img_src: String,
    page_img_alt: String,
    card_img_srcs_jpeg: [String],
    card_img_srcs_webp: [String],
    page_img_srcs_jpeg: [String],
    page_img_srcs_webp: [String],
    mini_img_srcs_jpeg: [String],
    mini_img_srcs_webp: [String],
    card_img_alts: [String],
    page_img_alts: [String],
    mini_img_alts: [String],
    url: String,
    school_homepage_url: String,
    price_calculator_url: String,
    state_jp: String,
    state_en: String,
    state_postcode: String,
    city: String,
    campus_address_short: String,
    year_type: String,
    school_type: String,
    rating_score: Number,
    ratings: Number,
    summary: String,
    location: { lat: Number, lon: Number },
    unique_flags: [
      {
        type: Schema.Types.ObjectId,
        ref: 'GroupChip',
      },
    ],
    admission_rate: Number,
    sat: { low: Number, average: Number, high: Number },
    cost: {
      academic_year_avg: String,
      in_state_tuition: String,
      out_of_state_tuition: String,
    },
    students: {
      size: String,
      men: Number,
      women: Number,
      entry_age_avg: Number,
      demographics: {
        white: Number,
        black: Number,
        hispanic: Number,
        asian: Number,
        international: Number,
        other: Number,
      },
    },
  },
})

module.exports = mongoose.model('Schools_v1', schools_v1Schema)
